/**
 * routes/workflowTemplateRoutes.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * API: Dynamic Workflow Template Builder
 *
 * Mount path: /api/admin/workflows
 *
 * Endpoints:
 *   POST /templates          — Save a complete template (nodes + edges) in one transaction
 *   GET  /templates          — List all templates (with node/edge counts)
 *   GET  /templates/:id      — Fetch a single template with full node/edge graph (for React Flow)
 *   PATCH /templates/:id/toggle — Activate / deactivate a template
 *   DELETE /templates/:id    — Hard-delete a template and all its nodes/edges (CASCADE)
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { Router, Response } from 'express';
import { z } from 'zod';
import { requireAdmin, requireSuperAdmin, AdminRequest } from '../middleware/auth.js';
import db from '../config/database.js';
import { recordAuditLog } from '../utils/auditLogger.js';

const router = Router();

// ── All template routes require at minimum a valid admin JWT ─────────────────
router.use(requireAdmin);

// ── Zod Schemas ──────────────────────────────────────────────────────────────

/** A single node as submitted from the React Flow canvas */
const NodeInputSchema = z.object({
  /** The temporary client-side ID generated by React Flow (e.g. "node-1") */
  client_id: z.string().min(1),
  step_name: z.string().min(1, 'ต้องระบุชื่อขั้นตอน'),
  assignee_type: z.enum(['USER', 'ROLE', 'AGENCY_HIERARCHY']),
  /** target_value is interpreted differently by assignee_type:
   *   USER             → admin a_id (numeric string)
   *   ROLE             → role name string (e.g. "HR_DIRECTOR")
   *   AGENCY_HIERARCHY → c_agency ag_id (numeric string)
   */
  target_value: z.string().optional().nullable(),
  ui_pos_x: z.number().default(0),
  ui_pos_y: z.number().default(0),
});

/** A single edge as submitted from the React Flow canvas */
const EdgeInputSchema = z.object({
  /** client_id of the source node — will be mapped to real DB node_id */
  source_client_id: z.string().min(1),
  /** client_id of the target node — will be mapped to real DB node_id */
  target_client_id: z.string().min(1),
  /** Optional condition label, e.g. 'APPROVED' | 'REJECTED' | null */
  condition_value: z.string().optional().nullable(),
});

const CreateTemplateSchema = z.object({
  name: z.string().min(1, 'ต้องระบุชื่อ Template'),
  description: z.string().optional().default(''),
  nodes: z.array(NodeInputSchema).min(1, 'ต้องมีอย่างน้อย 1 Node'),
  edges: z.array(EdgeInputSchema),
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/admin/workflows/templates
// สร้าง Workflow Template ใหม่ พร้อม Nodes + Edges ในครั้งเดียว (transaction)
// ─────────────────────────────────────────────────────────────────────────────
router.post('/templates', requireSuperAdmin, async (req: AdminRequest, res: Response): Promise<any> => {
  const parsed = CreateTemplateSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({
      status: false,
      message: 'ข้อมูลไม่ถูกต้อง',
      errors: parsed.error.flatten().fieldErrors,
    });
  }

  const { name, description, nodes, edges } = parsed.data;
  const adminId = req.admin!.id;

  const client = await db.connect();
  try {
    await client.query('BEGIN');

    // ── Step 1: Insert the template header ────────────────────────────────
    const { rows: [template] } = await client.query<{ template_id: number }>(
      `INSERT INTO workflow_templates (name, description, is_active, created_by, created_at, updated_at)
       VALUES ($1, $2, TRUE, $3, NOW(), NOW())
       RETURNING template_id`,
      [name, description, adminId],
    );
    const templateId = template.template_id;

    // ── Step 2: Insert nodes sequentially and build client_id → node_id map ─
    const clientIdToNodeId = new Map<string, number>();

    for (const node of nodes) {
      // Parse target_value to the correct column depending on assignee_type
      let targetRole: string | null = null;
      let targetAgencyId: number | null = null;
      let targetUserId: number | null = null;

      if (node.target_value) {
        switch (node.assignee_type) {
          case 'ROLE':
            targetRole = node.target_value;
            break;
          case 'AGENCY_HIERARCHY':
            targetAgencyId = parseInt(node.target_value, 10) || null;
            break;
          case 'USER':
            targetUserId = parseInt(node.target_value, 10) || null;
            break;
        }
      }

      const { rows: [insertedNode] } = await client.query<{ node_id: number }>(
        `INSERT INTO workflow_nodes
           (template_id, step_name, assignee_type, target_role, target_agency_id, target_user_id, ui_pos_x, ui_pos_y, created_at)
         VALUES ($1, $2, $3::wf_assignee_type, $4, $5, $6, $7, $8, NOW())
         RETURNING node_id`,
        [templateId, node.step_name, node.assignee_type, targetRole, targetAgencyId, targetUserId, node.ui_pos_x, node.ui_pos_y],
      );

      // Map the React Flow client_id to the real database node_id
      clientIdToNodeId.set(node.client_id, insertedNode.node_id);
    }

    // ── Step 3: Insert edges using the mapping dictionary ─────────────────
    for (const edge of edges) {
      const sourceNodeId = clientIdToNodeId.get(edge.source_client_id);
      const targetNodeId = clientIdToNodeId.get(edge.target_client_id);

      if (!sourceNodeId || !targetNodeId) {
        // An edge references a client_id not in the nodes array — fail fast
        await client.query('ROLLBACK');
        return res.status(400).json({
          status: false,
          message: `Edge อ้างอิง client_id ที่ไม่มีอยู่: source="${edge.source_client_id}", target="${edge.target_client_id}"`,
        });
      }

      await client.query(
        `INSERT INTO workflow_edges (template_id, source_node_id, target_node_id, condition_value)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT ON CONSTRAINT uq_wf_edge DO NOTHING`,
        [templateId, sourceNodeId, targetNodeId, edge.condition_value ?? null],
      );
    }

    await client.query('COMMIT');

    // Fire-and-forget audit log
    recordAuditLog({
      userId:         adminId,
      userName:       req.admin!.name,
      action:         'WORKFLOW_TEMPLATE_CREATE',
      targetResource: 'workflow_templates',
      targetId:       String(templateId),
      payload:        { name, node_count: nodes.length, edge_count: edges.length },
      ipAddress:      (req.ip as string) || null,
      userAgent:      (req.headers['user-agent'] as string) || null,
    });

    return res.status(201).json({
      status: true,
      message: `สร้าง Workflow Template "${name}" สำเร็จ`,
      response: {
        template_id:  templateId,
        name,
        node_count:   nodes.length,
        edge_count:   edges.length,
      },
    });
  } catch (err: any) {
    await client.query('ROLLBACK');
    console.error('[WorkflowTemplateRoutes] createTemplate error:', err.message);

    // Surface a friendly message for unique constraint violations
    if (err.code === '23505' && err.constraint === 'uq_wf_template_name') {
      return res.status(409).json({ status: false, message: `มี Template ชื่อ "${name}" อยู่แล้ว` });
    }
    return res.status(500).json({ status: false, message: 'ไม่สามารถบันทึก Workflow Template ได้' });
  } finally {
    client.release();
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/admin/workflows/templates
// ดึงรายการ templates ทั้งหมด (พร้อม count ของ nodes/edges)
// ─────────────────────────────────────────────────────────────────────────────
router.get('/templates', async (_req: AdminRequest, res: Response): Promise<any> => {
  try {
    const { rows } = await db.query(`
      SELECT
        t.template_id,
        t.name,
        t.description,
        t.is_active,
        t.created_at,
        t.updated_at,
        a.a_name          AS created_by_name,
        COUNT(DISTINCT n.node_id)::INT AS node_count,
        COUNT(DISTINCT e.edge_id)::INT AS edge_count
      FROM   workflow_templates t
      LEFT   JOIN admin a ON a.a_id = t.created_by
      LEFT   JOIN workflow_nodes n ON n.template_id = t.template_id
      LEFT   JOIN workflow_edges e ON e.template_id = t.template_id
      GROUP  BY t.template_id, a.a_name
      ORDER  BY t.is_active DESC, t.created_at DESC
    `);
    return res.json({ status: true, message: 'success', response: rows });
  } catch (err: any) {
    console.error('[WorkflowTemplateRoutes] list error:', err.message);
    return res.status(500).json({ status: false, message: 'โหลด Workflow Templates ไม่สำเร็จ' });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/admin/workflows/templates/:id
// ดึง template เดียว พร้อม nodes[] และ edges[] สำหรับ React Flow
// ─────────────────────────────────────────────────────────────────────────────
router.get('/templates/:id', async (req: AdminRequest, res: Response): Promise<any> => {
  const templateId = parseInt(String(req.params.id), 10);
  if (isNaN(templateId)) {
    return res.status(400).json({ status: false, message: 'template_id ไม่ถูกต้อง' });
  }

  try {
    const { rows: templates } = await db.query(
      `SELECT template_id, name, description, is_active, created_at, updated_at
       FROM   workflow_templates
       WHERE  template_id = $1`,
      [templateId],
    );
    if (!templates.length) {
      return res.status(404).json({ status: false, message: 'ไม่พบ Template' });
    }

    const { rows: nodes } = await db.query(
      `SELECT n.node_id, n.step_name, n.assignee_type, n.target_role,
              n.target_agency_id, n.target_user_id, n.ui_pos_x, n.ui_pos_y,
              a.a_name  AS target_user_name,
              ag.ag_name AS target_agency_name
       FROM   workflow_nodes n
       LEFT   JOIN admin a       ON a.a_id   = n.target_user_id
       LEFT   JOIN c_agency ag   ON ag.ag_id = n.target_agency_id
       WHERE  n.template_id = $1
       ORDER  BY n.node_id`,
      [templateId],
    );

    const { rows: edges } = await db.query(
      `SELECT edge_id, source_node_id, target_node_id, condition_value
       FROM   workflow_edges
       WHERE  template_id = $1
       ORDER  BY edge_id`,
      [templateId],
    );

    return res.json({
      status: true,
      message: 'success',
      response: { ...templates[0], nodes, edges },
    });
  } catch (err: any) {
    console.error('[WorkflowTemplateRoutes] get error:', err.message);
    return res.status(500).json({ status: false, message: 'โหลด Template ไม่สำเร็จ' });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// PATCH /api/admin/workflows/templates/:id/toggle
// เปิด / ปิดใช้งาน Template (SUPERADMIN only)
// ─────────────────────────────────────────────────────────────────────────────
router.patch('/templates/:id/toggle', requireSuperAdmin, async (req: AdminRequest, res: Response): Promise<any> => {
  const templateId = parseInt(String(req.params.id), 10);
  if (isNaN(templateId)) {
    return res.status(400).json({ status: false, message: 'template_id ไม่ถูกต้อง' });
  }

  const { is_active } = req.body;
  if (typeof is_active !== 'boolean') {
    return res.status(400).json({ status: false, message: 'ต้องส่ง is_active เป็น boolean' });
  }

  try {
    const { rowCount } = await db.query(
      `UPDATE workflow_templates SET is_active = $1, updated_at = NOW() WHERE template_id = $2`,
      [is_active, templateId],
    );
    if (rowCount === 0) return res.status(404).json({ status: false, message: 'ไม่พบ Template' });

    return res.json({
      status: true,
      message: is_active ? 'เปิดใช้งาน Template แล้ว' : 'ปิดใช้งาน Template แล้ว',
    });
  } catch (err: any) {
    console.error('[WorkflowTemplateRoutes] toggle error:', err.message);
    return res.status(500).json({ status: false, message: 'ไม่สามารถเปลี่ยนสถานะ Template ได้' });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// DELETE /api/admin/workflows/templates/:id
// ลบ Template ถาวร (CASCADE → nodes + edges ถูกลบอัตโนมัติ)
// ─────────────────────────────────────────────────────────────────────────────
router.delete('/templates/:id', requireSuperAdmin, async (req: AdminRequest, res: Response): Promise<any> => {
  const templateId = parseInt(String(req.params.id), 10);
  if (isNaN(templateId)) {
    return res.status(400).json({ status: false, message: 'template_id ไม่ถูกต้อง' });
  }

  try {
    const { rowCount } = await db.query(
      `DELETE FROM workflow_templates WHERE template_id = $1`,
      [templateId],
    );
    if (rowCount === 0) return res.status(404).json({ status: false, message: 'ไม่พบ Template' });

    recordAuditLog({
      userId:         req.admin!.id,
      userName:       req.admin!.name,
      action:         'WORKFLOW_TEMPLATE_DELETE',
      targetResource: 'workflow_templates',
      targetId:       String(templateId),
      payload:        null,
      ipAddress:      (req.ip as string) || null,
      userAgent:      (req.headers['user-agent'] as string) || null,
    });

    return res.json({ status: true, message: 'ลบ Workflow Template เรียบร้อยแล้ว' });
  } catch (err: any) {
    console.error('[WorkflowTemplateRoutes] delete error:', err.message);
    return res.status(500).json({ status: false, message: 'ไม่สามารถลบ Template ได้' });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/admin/workflows/circular/approve
// ลงนาม/อนุมัติเอกสารเวียน พร้อมรองรับ approval_context: SELF | ACTING
// (เป็น endpoint ที่ใช้แทน /api/admin/workflow/approve สำหรับ template-driven flow)
// ─────────────────────────────────────────────────────────────────────────────
const CircularApproveSchema = z.object({
  circular_id:      z.number().int().positive(),
  action:           z.enum(['APPROVE', 'REJECT', 'REQUEST_REVISION']),
  comment:          z.string().optional().default(''),
  approval_context: z.enum(['SELF', 'ACTING']).default('SELF'),
  /** Required when approval_context = 'ACTING' */
  delegation_id:    z.number().int().positive().optional(),
  /** Optional: the next inbox owner to assign to (for APPROVE/delegate action) */
  next_owner_id:    z.number().int().positive().optional(),
});

router.post('/circular/approve', requireAdmin, async (req: AdminRequest, res: Response): Promise<any> => {
  const parsed = CircularApproveSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({
      status: false,
      message: 'ข้อมูลไม่ถูกต้อง',
      errors: parsed.error.flatten().fieldErrors,
    });
  }

  const { circular_id, action, comment, approval_context, delegation_id, next_owner_id } = parsed.data;
  const actorId = req.admin!.id;

  // ── ACTING context: verify delegation is active and belongs to this user ──
  let resolvedDelegationId: number | null = null;
  if (approval_context === 'ACTING') {
    if (!delegation_id) {
      return res.status(400).json({
        status: false,
        message: 'ต้องระบุ delegation_id เมื่อลงนามในฐานะรักษาการ',
      });
    }

    const { rows: delRows } = await db.query(
      `SELECT d.delegation_id, d.delegated_role, d.assigner_id,
              assigner.a_name AS assigner_name
       FROM   c_workflow_delegations d
       JOIN   admin assigner ON assigner.a_id = d.assigner_id
       WHERE  d.delegation_id = $1
         AND  d.assignee_id   = $2
         AND  d.is_active     = TRUE`,
      [delegation_id, actorId],
    );

    if (!delRows.length) {
      return res.status(403).json({
        status: false,
        message: 'ไม่พบการมอบอำนาจที่ถูกต้องสำหรับบัญชีนี้ หรือถูกยกเลิกแล้ว',
      });
    }
    resolvedDelegationId = delRows[0].delegation_id;
  }

  const client = await db.connect();
  try {
    await client.query('BEGIN');

    // ── Fetch the current inbox item for this circular ────────────────────
    const { rows: inboxRows } = await client.query(
      `SELECT inbox_id, status
       FROM   c_workflow_inbox
       WHERE  circular_id      = $1
         AND  current_owner_id = $2
         AND  status           = 'PENDING'
       ORDER  BY created_at DESC
       LIMIT  1`,
      [circular_id, actorId],
    );

    if (!inboxRows.length) {
      await client.query('ROLLBACK');
      return res.status(404).json({
        status: false,
        message: 'ไม่พบรายการใน Inbox สำหรับเอกสารเลขนี้ หรือถูกดำเนินการไปแล้ว',
      });
    }

    const inboxId = inboxRows[0].inbox_id;

    // ── Map action to inbox status ────────────────────────────────────────
    const newStatus: Record<string, string> = {
      APPROVE:          'APPROVED',
      REJECT:           'REJECTED',
      REQUEST_REVISION: 'REJECTED',
    };
    const resolvedStatus = newStatus[action] ?? 'APPROVED';

    // ── Update inbox entry ────────────────────────────────────────────────
    await client.query(
      `UPDATE c_workflow_inbox
       SET    status     = $1::workflow_inbox_status,
              updated_at = NOW()
       WHERE  inbox_id   = $2`,
      [resolvedStatus, inboxId],
    );

    // ── Update circular workflow status ───────────────────────────────────
    const circularStatus = action === 'APPROVE' ? 'APPROVED' : 'REVISION_NEEDED';
    await client.query(
      `UPDATE c_information
       SET    in_workflow_status = $1,
              in_current_owner_id = $2,
              updated_at = NOW()
       WHERE  in_id = $3`,
      [circularStatus, next_owner_id ?? actorId, circular_id],
    );

    // ── If approved and a next_owner_id is provided, create new inbox item ─
    if (action === 'APPROVE' && next_owner_id) {
      await client.query(
        `INSERT INTO c_workflow_inbox
           (circular_id, current_owner_id, assigned_as, from_stage, status, created_at, updated_at)
         VALUES ($1, $2, 'SELF', $3, 'PENDING', NOW(), NOW())`,
        [circular_id, next_owner_id, `ส่งต่อจาก ${req.admin!.name} (${action})`],
      );
    }

    await client.query('COMMIT');

    // ── Fire-and-forget audit log ─────────────────────────────────────────
    recordAuditLog({
      userId:           actorId,
      userName:         req.admin!.name,
      action:           `CIRCULAR_${action}`,
      targetResource:   'c_workflow_inbox',
      targetId:         String(circular_id),
      payload:          { circular_id, action, comment, approval_context, next_owner_id },
      ipAddress:        (req.ip as string) || null,
      userAgent:        (req.headers['user-agent'] as string) || null,
      isActing:         approval_context === 'ACTING',
      approval_context: approval_context,
      delegation_id:    resolvedDelegationId,
    });

    return res.json({
      status: true,
      message: action === 'APPROVE'
        ? `ลงนามอนุมัติสำเร็จ (บริบท: ${approval_context === 'ACTING' ? 'รักษาการ' : 'ตนเอง'})`
        : `ดำเนินการ ${action} สำเร็จ`,
    });
  } catch (err: any) {
    await client.query('ROLLBACK');
    console.error('[WorkflowTemplateRoutes] circular/approve error:', err.message);
    return res.status(500).json({ status: false, message: 'ไม่สามารถดำเนินการได้' });
  } finally {
    client.release();
  }
});

export default router;
